version: '2'
services:
  adventquiz-app:
    image: adventquiz
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://adventquiz-postgresql:5432/AdventQuiz
      - SPRING_APPLICATION_JSON={
        "spring.mail.password":"AdventQuiz1234",
        "jhipster.mail.base-url":"https://advent.iblsoft.com"
        }
    ports:
      - 8080:8080
    depends_on:
      - adventquiz-postgresql
  adventquiz-postgresql:
    extends:
      file: postgresql.yml
      service: adventquiz-postgresql
